import type { Metadata } from "next";
import "./globals.css";
import AlbertSans from "next/font/local";

const albertSans = AlbertSans({
  src: "../public/fonts/AlbertSans.ttf",
  variable: '--font-custom',
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${albertSans.className} h-full antialiased mt-9`}>
      <body className="min-h-full">{children}</body>
    </html>
  );
}
